-- Phase 4 -- frame counts + native pixel size per species/side,
-- generated directly from the lossless slicing pass
-- (assets/front/<ID>/NNN.png, assets/back/<ID>/NNN.png -- crop-only,
-- no resize, every frame preserves its source pixels exactly).
-- Frame counts and native sizes both vary per species -- the source
-- sheets carry no fixed convention, confirmed by direct measurement.
-- main.lua computes each species battleScaleFront/battleScaleBack
-- from the size fields here (56 / native size), so on-screen
-- sizing is consistent WITHOUT resampling any pixel data --
-- see BattleState.lua BATTLE_SCALE_DEFAULT/resolveBattleScale in
-- the real engine source for the confirmed scale semantics.

return {
  PICHU = { front = 57, frontSize = 49, back = 57, backSize = 49 },
  MUNCHLAX = { front = 71, frontSize = 48, back = 71, backSize = 50 },
  TRUBBISH = { front = 102, frontSize = 53, back = 102, backSize = 59 },
  GARBODOR = { front = 68, frontSize = 93, back = 67, backSize = 102 },
  MELTAN = { front = 53, frontSize = 38, back = 105, backSize = 48 },
  MELMETAL = { front = 28, frontSize = 101, back = 10, backSize = 120 },
  GROOKEY = { front = 56, frontSize = 96, back = 56, backSize = 96 },
  THWACKEY = { front = 83, frontSize = 58, back = 83, backSize = 55 },
  RILLABOOM = { front = 12, frontSize = 96, back = 10, backSize = 96 },
  SCORBUNNY = { front = 73, frontSize = 96, back = 73, backSize = 72 },
  RABOOT = { front = 60, frontSize = 58, back = 60, backSize = 57 },
  CINDERACE = { front = 12, frontSize = 96, back = 10, backSize = 96 },
  SOBBLE = { front = 45, frontSize = 96, back = 45, backSize = 49 },
  DRIZZILE = { front = 139, frontSize = 53, back = 92, backSize = 53 },
  INTELEON = { front = 95, frontSize = 80, back = 95, backSize = 79 },
  ROOKIDEE = { front = 84, frontSize = 96, back = 84, backSize = 65 },
  CORVISQUIRE = { front = 18, frontSize = 93, back = 18, backSize = 92 },
  CORVIKNIGHT = { front = 97, frontSize = 96, back = 97, backSize = 70 },
  BLIPBUG = { front = 10, frontSize = 45, back = 10, backSize = 46 },
  DOTTLER = { front = 49, frontSize = 96, back = 48, backSize = 96 },
  ORBEETLE = { front = 18, frontSize = 96, back = 10, backSize = 96 },
  CHEWTLE = { front = 55, frontSize = 47, back = 55, backSize = 49 },
  DREDNAW = { front = 39, frontSize = 96, back = 39, backSize = 77 },
  ROLYCOLY = { front = 41, frontSize = 96, back = 41, backSize = 53 },
  CARKOL = { front = 91, frontSize = 65, back = 91, backSize = 64 },
  COALOSSAL = { front = 92, frontSize = 84, back = 92, backSize = 83 },
  APPLIN = { front = 110, frontSize = 42, back = 126, backSize = 44 },
  FLAPPLE = { front = 43, frontSize = 96, back = 8, backSize = 96 },
  APPLETUN = { front = 42, frontSize = 96, back = 7, backSize = 96 },
  SILICOBRA = { front = 70, frontSize = 50, back = 70, backSize = 59 },
  SANDACONDA = { front = 132, frontSize = 87, back = 133, backSize = 84 },
  TOXEL = { front = 14, frontSize = 96, back = 13, backSize = 50 },
  TOXTRICITY = { front = 60, frontSize = 85, back = 10, backSize = 96 },
  SIZZLIPEDE = { front = 77, frontSize = 96, back = 8, backSize = 96 },
  CENTISKORCH = { front = 24, frontSize = 96, back = 24, backSize = 96 },
  HATENNA = { front = 17, frontSize = 96, back = 17, backSize = 47 },
  HATTREM = { front = 32, frontSize = 96, back = 12, backSize = 96 },
  HATTERENE = { front = 84, frontSize = 83, back = 16, backSize = 96 },
  IMPIDIMP = { front = 59, frontSize = 54, back = 59, backSize = 53 },
  MORGREM = { front = 12, frontSize = 96, back = 10, backSize = 96 },
  GRIMMSNARL = { front = 66, frontSize = 93, back = 66, backSize = 85 },
  MILCERY = { front = 57, frontSize = 96, back = 25, backSize = 96 },
  ALCREMIE = { front = 104, frontSize = 70, back = 10, backSize = 96 },
  CUFANT = { front = 80, frontSize = 78, back = 80, backSize = 72 },
  COPPERAJAH = { front = 12, frontSize = 96, back = 10, backSize = 96 },
  DURALUDON = { front = 8, frontSize = 96, back = 8, backSize = 76 },
  ETERNATUS = { front = 120, frontSize = 111, back = 120, backSize = 123 },
  KUBFU = { front = 32, frontSize = 96, back = 12, backSize = 96 },
  URSHIFU = { front = 32, frontSize = 96, back = 16, backSize = 96 },
  GOSSIFLEUR = { front = 12, frontSize = 96, back = 57, backSize = 96 },
  ELDEGOSS = { front = 49, frontSize = 72, back = 49, backSize = 96 },
}
