-- The engine's native, cart-baked-in species roster -- Kanto 151 (gen1recomp-
-- dev's own ROM-extracted generated pokemon.lua) plus Johto 152-251
-- (tools/rom_manifest_gold.json's pokemonAssets keys, 2 mis-spelled Kanto
-- duplicates dropped -- pokemon.lua's own spelling wins). Same list, same
-- methodology, tools/generate_sprite_pack_data.ps1 already used to classify
-- Phase 1's plain-token resolution as "native-vanilla" vs "national_dex" --
-- generated fresh here as its own standalone file because main.lua's sprite
-- priority logic needs this exact distinction at runtime (native-vanilla ids
-- rank BELOW this mod's own pack; national_dex-added ids rank ABOVE it, when
-- NATIONAL DEX SPRITES is on -- see installSpriteAssetPacks).
return {
  "ABRA", "AERODACTYL", "ALAKAZAM", "ARBOK", "ARCANINE", "ARTICUNO",
  "BEEDRILL", "BELLSPROUT", "BLASTOISE", "BULBASAUR", "BUTTERFREE", "CATERPIE",
  "CHANSEY", "CHARIZARD", "CHARMANDER", "CHARMELEON", "CLEFABLE", "CLEFAIRY",
  "CLOYSTER", "CUBONE", "DEWGONG", "DIGLETT", "DITTO", "DODRIO",
  "DODUO", "DRAGONAIR", "DRAGONITE", "DRATINI", "DROWZEE", "DUGTRIO",
  "EEVEE", "EKANS", "ELECTABUZZ", "ELECTRODE", "EXEGGCUTE", "EXEGGUTOR",
  "FARFETCHD", "FEAROW", "FLAREON", "GASTLY", "GENGAR", "GEODUDE",
  "GLOOM", "GOLBAT", "GOLDEEN", "GOLDUCK", "GOLEM", "GRAVELER",
  "GRIMER", "GROWLITHE", "GYARADOS", "HAUNTER", "HITMONCHAN", "HITMONLEE",
  "HORSEA", "HYPNO", "IVYSAUR", "JIGGLYPUFF", "JOLTEON", "JYNX",
  "KABUTO", "KABUTOPS", "KADABRA", "KAKUNA", "KANGASKHAN", "KINGLER",
  "KOFFING", "KRABBY", "LAPRAS", "LICKITUNG", "MACHAMP", "MACHOKE",
  "MACHOP", "MAGIKARP", "MAGMAR", "MAGNEMITE", "MAGNETON", "MANKEY",
  "MAROWAK", "MEOWTH", "METAPOD", "MEW", "MEWTWO", "MOLTRES",
  "MR_MIME", "MUK", "NIDOKING", "NIDOQUEEN", "NIDORAN_F", "NIDORAN_M",
  "NIDORINA", "NIDORINO", "NINETALES", "ODDISH", "OMANYTE", "OMASTAR",
  "ONIX", "PARAS", "PARASECT", "PERSIAN", "PIDGEOT", "PIDGEOTTO",
  "PIDGEY", "PIKACHU", "PINSIR", "POLIWAG", "POLIWHIRL", "POLIWRATH",
  "PONYTA", "PORYGON", "PRIMEAPE", "PSYDUCK", "RAICHU", "RAPIDASH",
  "RATICATE", "RATTATA", "RHYDON", "RHYHORN", "SANDSHREW", "SANDSLASH",
  "SCYTHER", "SEADRA", "SEAKING", "SEEL", "SHELLDER", "SLOWBRO",
  "SLOWPOKE", "SNORLAX", "SPEAROW", "SQUIRTLE", "STARMIE", "STARYU",
  "TANGELA", "TAUROS", "TENTACOOL", "TENTACRUEL", "VAPOREON", "VENOMOTH",
  "VENONAT", "VENUSAUR", "VICTREEBEL", "VILEPLUME", "VOLTORB", "VULPIX",
  "WARTORTLE", "WEEDLE", "WEEPINBELL", "WEEZING", "WIGGLYTUFF", "ZAPDOS",
  "ZUBAT", "AIPOM", "AMPHAROS", "ARIADOS", "AZUMARILL", "BAYLEEF",
  "BELLOSSOM", "BLISSEY", "CELEBI", "CHIKORITA", "CHINCHOU", "CLEFFA",
  "CORSOLA", "CROBAT", "CROCONAW", "CYNDAQUIL", "DELIBIRD", "DONPHAN",
  "DUNSPARCE", "ELEKID", "ENTEI", "ESPEON", "FERALIGATR", "FLAAFFY",
  "FORRETRESS", "FURRET", "GIRAFARIG", "GLIGAR", "GRANBULL", "HERACROSS",
  "HITMONTOP", "HOOTHOOT", "HOPPIP", "HOUNDOOM", "HOUNDOUR", "HO_OH",
  "IGGLYBUFF", "JUMPLUFF", "KINGDRA", "LANTURN", "LARVITAR", "LEDIAN",
  "LEDYBA", "LUGIA", "MAGBY", "MAGCARGO", "MANTINE", "MAREEP",
  "MARILL", "MEGANIUM", "MILTANK", "MISDREAVUS", "MURKROW", "NATU",
  "NOCTOWL", "OCTILLERY", "PHANPY", "PICHU", "PILOSWINE", "PINECO",
  "POLITOED", "PORYGON2", "PUPITAR", "QUAGSIRE", "QUILAVA", "QWILFISH",
  "RAIKOU", "REMORAID", "SCIZOR", "SENTRET", "SHUCKLE", "SKARMORY",
  "SKIPLOOM", "SLOWKING", "SLUGMA", "SMEARGLE", "SMOOCHUM", "SNEASEL",
  "SNUBBULL", "SPINARAK", "STANTLER", "STEELIX", "SUDOWOODO", "SUICUNE",
  "SUNFLORA", "SUNKERN", "SWINUB", "TEDDIURSA", "TOGEPI", "TOGETIC",
  "TOTODILE", "TYPHLOSION", "TYRANITAR", "TYROGUE", "UMBREON", "UNOWN",
  "URSARING", "WOBBUFFET", "WOOPER", "XATU", "YANMA",
}