-- Cosmetic FEMALE battle-sprite lookup, keyed by BASE species id.
--
-- These are NOT separate species/content ids -- national_dex has no
-- registered '<ID>_FEMALE' record for any species listed here (the 4
-- species that DO have a real separate _FEMALE id -- Meowstic, Indeedee,
-- Basculegion, Oinkologne -- are wired as ordinary distinct roster entries
-- in sprite_pack_roster_full.lua instead, not through this table).
--
-- Purely a battle-time cosmetic sprite swap: a later phase should check the
-- battler's rolled gender, and if female AND this table has an entry for
-- that species, source live battle frames from assets/<side>/<folderToken>/
-- instead of assets/<side>/<ID>/ -- falling back to the base id's art if the
-- species has no entry here, same silent-safe-fallback convention already
-- used elsewhere in this pipeline. Not wired up anywhere yet -- Phase 1
-- only produces this data; the hook lands in a later phase.

return {
  ABOMASNOW = { folder = "ABOMASNOW_F", front = 41, frontSize = 95, back = 40, backSize = 94 },
  AIPOM = { folder = "AIPOM_F", front = 39, frontSize = 58, back = 39, backSize = 54 },
  ALAKAZAM = { folder = "ALAKAZAM_F", front = 53, frontSize = 93, back = 52, backSize = 82 },
  AMBIPOM = { folder = "AMBIPOM_F", front = 96, frontSize = 87, back = 96, backSize = 89 },
  BEAUTIFLY = { folder = "BEAUTIFLY_F", front = 77, frontSize = 78, back = 77, backSize = 81 },
  BIBAREL = { folder = "BIBAREL_F", front = 81, frontSize = 71, back = 83, backSize = 68 },
  BIDOOF = { folder = "BIDOOF_F", front = 51, frontSize = 48, back = 52, backSize = 51 },
  BLAZIKEN = { folder = "BLAZIKEN_F", front = 56, frontSize = 74, back = 57, backSize = 73 },
  BUIZEL = { folder = "BUIZEL_F", front = 60, frontSize = 49, back = 60, backSize = 49 },
  BUTTERFREE = { folder = "BUTTERFREE_F", front = 44, frontSize = 62, back = 14, backSize = 64 },
  CACTURNE = { folder = "CACTURNE_F", front = 57, frontSize = 70, back = 57, backSize = 71 },
  CAMERUPT = { folder = "CAMERUPT_F", front = 53, frontSize = 79, back = 55, backSize = 82 },
  COMBEE = { folder = "COMBEE_F", front = 16, frontSize = 67, back = 16, backSize = 67 },
  COMBUSKEN = { folder = "COMBUSKEN_F", front = 124, frontSize = 71, back = 62, backSize = 72 },
  CROAGUNK = { folder = "CROAGUNK_F", front = 77, frontSize = 50, back = 77, backSize = 52 },
  DODRIO = { folder = "DODRIO_F", front = 77, frontSize = 76, back = 77, backSize = 76 },
  DODUO = { folder = "DODUO_F", front = 94, frontSize = 60, back = 95, backSize = 61 },
  DONPHAN = { folder = "DONPHAN_F", front = 63, frontSize = 82, back = 63, backSize = 90 },
  DUSTOX = { folder = "DUSTOX_F", front = 82, frontSize = 80, back = 81, backSize = 78 },
  EEVEE = { folder = "EEVEE_F", front = 125, frontSize = 49, back = 133, backSize = 50 },
  FINNEON = { folder = "FINNEON_F", front = 87, frontSize = 77, back = 87, backSize = 73 },
  FLOATZEL = { folder = "FLOATZEL_F", front = 84, frontSize = 71, back = 84, backSize = 70 },
  FRILLISH = { folder = "FRILLISH_F", front = 82, frontSize = 70, back = 82, backSize = 70 },
  GABITE = { folder = "GABITE_F", front = 27, frontSize = 71, back = 27, backSize = 72 },
  GARCHOMP = { folder = "GARCHOMP_F", front = 44, frontSize = 82, back = 45, backSize = 89 },
  GIBLE = { folder = "GIBLE_F", front = 63, frontSize = 57, back = 63, backSize = 51 },
  GIRAFARIG = { folder = "GIRAFARIG_F", front = 52, frontSize = 76, back = 32, backSize = 77 },
  GLIGAR = { folder = "GLIGAR_F", front = 34, frontSize = 93, back = 33, backSize = 92 },
  GLOOM = { folder = "GLOOM_F", front = 48, frontSize = 51, back = 48, backSize = 49 },
  GOLBAT = { folder = "GOLBAT_F", front = 8, frontSize = 111, back = 8, backSize = 95 },
  GOLDEEN = { folder = "GOLDEEN_F", front = 57, frontSize = 75, back = 57, backSize = 75 },
  GULPIN = { folder = "GULPIN_F", front = 49, frontSize = 40, back = 47, backSize = 39 },
  GYARADOS = { folder = "GYARADOS_F", front = 43, frontSize = 102, back = 43, backSize = 108 },
  HERACROSS = { folder = "HERACROSS_F", front = 42, frontSize = 64, back = 42, backSize = 70 },
  HIPPOPOTAS = { folder = "HIPPOPOTAS_F", front = 94, frontSize = 65, back = 95, backSize = 58 },
  HIPPOWDON = { folder = "HIPPOWDON_F", front = 45, frontSize = 84, back = 47, backSize = 96 },
  HOUNDOOM = { folder = "HOUNDOOM_F", front = 53, frontSize = 77, back = 48, backSize = 80 },
  HYPNO = { folder = "HYPNO_F", front = 62, frontSize = 66, back = 62, backSize = 65 },
  JELLICENT = { folder = "JELLICENT_F", front = 68, frontSize = 86, back = 69, backSize = 87 },
  KADABRA = { folder = "KADABRA_F", front = 60, frontSize = 79, back = 60, backSize = 80 },
  KRICKETOT = { folder = "KRICKETOT_F", front = 75, frontSize = 45, back = 75, backSize = 47 },
  KRICKETUNE = { folder = "KRICKETUNE_F", front = 51, frontSize = 69, back = 51, backSize = 69 },
  LEDIAN = { folder = "LEDIAN_F", front = 40, frontSize = 62, back = 40, backSize = 61 },
  LEDYBA = { folder = "LEDYBA_F", front = 48, frontSize = 48, back = 48, backSize = 46 },
  LUDICOLO = { folder = "LUDICOLO_F", front = 38, frontSize = 85, back = 42, backSize = 79 },
  LUMINEON = { folder = "LUMINEON_F", front = 86, frontSize = 73, back = 86, backSize = 83 },
  LUXIO = { folder = "LUXIO_F", front = 96, frontSize = 67, back = 96, backSize = 63 },
  LUXRAY = { folder = "LUXRAY_F", front = 85, frontSize = 76, back = 86, backSize = 73 },
  MAGIKARP = { folder = "MAGIKARP_F", front = 60, frontSize = 63, back = 58, backSize = 66 },
  MAMOSWINE = { folder = "MAMOSWINE_F", front = 83, frontSize = 83, back = 73, backSize = 81 },
  MEDICHAM = { folder = "MEDICHAM_F", front = 45, frontSize = 73, back = 44, backSize = 72 },
  MEDITITE = { folder = "MEDITITE_F", front = 143, frontSize = 54, back = 144, backSize = 51 },
  MEGANIUM = { folder = "MEGANIUM_F", front = 45, frontSize = 82, back = 44, backSize = 80 },
  MILOTIC = { folder = "MILOTIC_F", front = 95, frontSize = 86, back = 100, backSize = 93 },
  MURKROW = { folder = "MURKROW_F", front = 30, frontSize = 44, back = 31, backSize = 45 },
  NUMEL = { folder = "NUMEL_F", front = 24, frontSize = 48, back = 25, backSize = 53 },
  NUZLEAF = { folder = "NUZLEAF_F", front = 47, frontSize = 58, back = 44, backSize = 54 },
  OCTILLERY = { folder = "OCTILLERY_F", front = 17, frontSize = 67, back = 16, backSize = 79 },
  PACHIRISU = { folder = "PACHIRISU_F", front = 56, frontSize = 55, back = 56, backSize = 57 },
  PIKACHU = { folder = "PIKACHU_F", front = 56, frontSize = 51, back = 57, backSize = 47 },
  PILOSWINE = { folder = "PILOSWINE_F", front = 35, frontSize = 56, back = 33, backSize = 56 },
  POLITOED = { folder = "POLITOED_F", front = 48, frontSize = 79, back = 97, backSize = 81 },
  PYROAR = { folder = "PYROAR_F", front = 90, frontSize = 80, back = 90, backSize = 89 },
  QUAGSIRE = { folder = "QUAGSIRE_F", front = 37, frontSize = 69, back = 34, backSize = 70 },
  RAICHU = { folder = "RAICHU_F", front = 84, frontSize = 73, back = 84, backSize = 73 },
  RATICATE = { folder = "RATICATE_F", front = 59, frontSize = 62, back = 59, backSize = 66 },
  RATTATA = { folder = "RATTATA_F", front = 51, frontSize = 43, back = 50, backSize = 57 },
  RELICANTH = { folder = "RELICANTH_F", front = 57, frontSize = 59, back = 57, backSize = 57 },
  RHYDON = { folder = "RHYDON_F", front = 96, frontSize = 78, back = 97, backSize = 81 },
  RHYHORN = { folder = "RHYHORN_F", front = 76, frontSize = 66, back = 83, backSize = 72 },
  RHYPERIOR = { folder = "RHYPERIOR_F", front = 126, frontSize = 83, back = 126, backSize = 93 },
  ROSELIA = { folder = "ROSELIA_F", front = 61, frontSize = 62, back = 49, backSize = 60 },
  ROSERADE = { folder = "ROSERADE_F", front = 102, frontSize = 71, back = 102, backSize = 69 },
  SCIZOR = { folder = "SCIZOR_F", front = 53, frontSize = 75, back = 53, backSize = 75 },
  SCYTHER = { folder = "SCYTHER_F", front = 69, frontSize = 61, back = 69, backSize = 69 },
  SEAKING = { folder = "SEAKING_F", front = 48, frontSize = 72, back = 48, backSize = 94 },
  SHIFTRY = { folder = "SHIFTRY_F", front = 54, frontSize = 99, back = 53, backSize = 100 },
  SHINX = { folder = "SHINX_F", front = 64, frontSize = 51, back = 64, backSize = 55 },
  SNEASEL = { folder = "SNEASEL_F", front = 56, frontSize = 56, back = 56, backSize = 56 },
  SNEASEL_HISUI = { folder = "SNEASEL_1_F", front = 49, frontSize = 53, back = 11, backSize = 96 },
  SNOVER = { folder = "SNOVER_F", front = 56, frontSize = 71, back = 55, backSize = 74 },
  STARAPTOR = { folder = "STARAPTOR_F", front = 47, frontSize = 69, back = 46, backSize = 73 },
  STARAVIA = { folder = "STARAVIA_F", front = 57, frontSize = 53, back = 58, backSize = 52 },
  STARLY = { folder = "STARLY_F", front = 49, frontSize = 40, back = 49, backSize = 41 },
  STEELIX = { folder = "STEELIX_F", front = 48, frontSize = 93, back = 48, backSize = 97 },
  SUDOWOODO = { folder = "SUDOWOODO_F", front = 33, frontSize = 66, back = 34, backSize = 69 },
  SWALOT = { folder = "SWALOT_F", front = 50, frontSize = 63, back = 50, backSize = 61 },
  TANGROWTH = { folder = "TANGROWTH_F", front = 95, frontSize = 98, back = 95, backSize = 98 },
  TORCHIC = { folder = "TORCHIC_F", front = 74, frontSize = 46, back = 74, backSize = 46 },
  TOXICROAK = { folder = "TOXICROAK_F", front = 64, frontSize = 67, back = 64, backSize = 71 },
  UNFEZANT = { folder = "UNFEZANT_F", front = 75, frontSize = 72, back = 77, backSize = 74 },
  URSARING = { folder = "URSARING_F", front = 62, frontSize = 80, back = 62, backSize = 78 },
  VENUSAUR = { folder = "VENUSAUR_F", front = 83, frontSize = 86, back = 84, backSize = 89 },
  VILEPLUME = { folder = "VILEPLUME_F", front = 35, frontSize = 56, back = 35, backSize = 56 },
  WEAVILE = { folder = "WEAVILE_F", front = 130, frontSize = 81, back = 64, backSize = 77 },
  WOBBUFFET = { folder = "WOBBUFFET_F", front = 61, frontSize = 57, back = 60, backSize = 64 },
  WOOPER = { folder = "WOOPER_F", front = 48, frontSize = 40, back = 48, backSize = 40 },
  XATU = { folder = "XATU_F", front = 48, frontSize = 60, back = 49, backSize = 67 },
  ZUBAT = { folder = "ZUBAT_F", front = 27, frontSize = 53, back = 27, backSize = 59 },
}
