# Build-time-only tool, not shipped mod logic (same convention as
# parse_base_exp.ps1/generate_sprite_pack_data.ps1). Extends
# assets/overworld/'s existing single-frame-per-direction roster (down/
# left/up, frame 1 only -- built by an earlier, scratchpad-only pair of
# scripts, gen_full_roster_overworld.ps1 + gen_directional_overworld.ps1,
# whose row/column convention this reuses exactly) to a full 4-frame walk
# cycle per direction, so the draw code can animate walking AND idle
# instead of showing one static crop per facing.
#
# Source: Overworld_Sprites/Followers/<ID>.png, confirmed by direct visual
# inspection (PIKACHU.png) to be a 256x256, 4-column x 4-row grid, 64x64
# per cell -- the standard RPG Maker character-sheet layout. Row0 = down/
# front, Row1 = left profile, Row2 = right profile (skipped: this mod's
# existing convention is right = left mirrored at draw time, e.g.
# SpriteRenderer's own WALK/STAND tables and loadOverworldImage's own
# "_left" reuse), Row3 = up/back. Columns 0-3 are the 4 walk-cycle frames.
#
# Output naming extends the existing convention exactly: column 0 (already
# on disk as <ID>.png / <ID>_left.png / <ID>_up.png, generated by the
# earlier scripts) is "frame 1", implicit/no numeric infix. Columns 1-3
# become frames 2-4, infixed BEFORE the direction suffix (matching the
# 000-placeholder set's own established _2 naming from earlier this
# session): <ID>_2.png / _3 / _4 (down), <ID>_2_left.png / _3_left / _4_left,
# <ID>_2_up.png / _3_up / _4_up. Idempotent (skips any file already
# present), so re-running after adding new source sheets only fills gaps.
#
# "000" (the hand-generated 16x16 white-square-X generic fallback,
# explicit user instruction earlier this session) is deliberately EXCLUDED
# even though Overworld_Sprites/Followers/000.png exists -- that identity
# is a simple hand-authored placeholder reused across every slot on
# purpose, not a real 4-frame animation, and must not be overwritten by
# whatever art actually lives in the source pack's own "000" slot.
#
# Rerun this whenever Overworld_Sprites/Followers gains new species.

Add-Type -AssemblyName System.Drawing

$srcDir = "C:\Proyectos\DynamaxRecomp\Overworld_Sprites\Followers"
$dstDir = "C:\Proyectos\DynamaxRecomp\GalarGmaxDex\assets\overworld"

# row index (0-based) -> output direction suffix ("" = down, no suffix)
$ROWS = @(
  @{ row = 0; suffix = "" },
  @{ row = 1; suffix = "_left" },
  @{ row = 3; suffix = "_up" }
)
# column index (0-based) -> output frame infix ("" = frame 1, col 0,
# already on disk from the earlier scripts and never regenerated here)
$COLS = @(
  @{ col = 0; infix = "" },
  @{ col = 1; infix = "_2" },
  @{ col = 2; infix = "_3" },
  @{ col = 3; infix = "_4" }
)

$files = Get-ChildItem "$srcDir\*.png" | Where-Object { $_.BaseName -ne "000" }
$generated = 0
$alreadyPresent = 0
$failed = @()
$i = 0

foreach ($f in $files) {
    $i++
    $id = $f.BaseName
    $sheet = $null
    try {
        foreach ($r in $ROWS) {
            foreach ($c in $COLS) {
                if ($c.infix -eq "" -and $r.suffix -eq "") { continue } # frame1 down already exists
                $dstPath = "$dstDir\${id}$($c.infix)$($r.suffix).png"
                if (Test-Path $dstPath) { $alreadyPresent++; continue }
                if (-not $sheet) {
                    $sheet = [System.Drawing.Bitmap]::FromFile($f.FullName)
                }
                $tw = [int]($sheet.Width / 4)
                $th = [int]($sheet.Height / 4)
                $rect = New-Object System.Drawing.Rectangle(($c.col * $tw), ($r.row * $th), $tw, $th)
                $tile = $sheet.Clone($rect, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
                $tile.Save($dstPath, [System.Drawing.Imaging.ImageFormat]::Png)
                $tile.Dispose()
                $generated++
            }
        }
        if ($sheet) { $sheet.Dispose() }
    } catch {
        $failed += "$id ($_)"
    }
    if ($i % 200 -eq 0) { Write-Output "...$i / $($files.Count)" }
}

Write-Output "Generated: $generated new frame files"
Write-Output "Already present (skipped): $alreadyPresent"
if ($failed.Count -gt 0) {
    Write-Output "Failed ($($failed.Count)):"
    $failed | Select-Object -First 20 | ForEach-Object { Write-Output "  $_" }
}
