<#
  generate_sprite_pack_data.ps1

  BUILD-TIME-ONLY TOOL -- not shipped mod logic, not loaded by the game.
  Run this offline, directly against the checked-out repos on disk, whenever
  new folders are added under GalarGmaxDex/assets/front|back/ and the
  full-roster sprite pack data needs regenerating.

  What it does (Phase 1 of the full-roster battle sprite pack plan):
    1. Builds the authoritative "native vanilla" species id list (Kanto 151
       from gen1recomp-dev's own ROM-extracted data/generated/pokemon.lua,
       plus the 100 Johto-only ids from tools/rom_manifest_gold.json's
       pokemonAssets key set, cross-validated against national_dex's own
       register table so the exact spelling convention is confirmed).
    2. Parses national_dex's data/species/generated/national.lua into a flat
       record list (id, dex, form, baseSpecies, section) so folder tokens
       can be cross-referenced against real registered content instead of
       guessed.
    3. Enumerates every GalarGmaxDex/assets/front/<TOKEN> folder, categorizes
       each token (plain / mega-family / female "_F" / numeric-suffix), and
       resolves each to a real content id using ONLY verifiable evidence:
         - plain: exact id match (with a verified, collision-free
           underscore-stripping normalization pass for tokens whose folder
           name dropped an underscore national_dex/the engine keeps, e.g.
           HOOH -> HO_OH, TAPUKOKO -> TAPU_KOKO -- confirmed zero collisions
           across the full ~1600-id universe before this pass is trusted).
         - mega-family: baseSpecies+form cross-reference against
           national.lua's register table.
         - numeric-suffix: tiered (Tier 1 mechanical single-form identity
           match; Tier 2 a short, individually-verified hand list for
           well-known multi-form species; Tier 3 skip+log everything left).
         - "_F": cosmetic-female bucket (base species -> folder), except the
           4 species with a REAL separate "_FEMALE" id in national_dex.
    4. Measures front/back frame counts and first-frame native pixel size
       for every resolved id and every genuine "_F" cosmetic folder, via
       System.Drawing.Image (no resampling, just reading existing PNGs).
    5. Emits species/sprite_pack_roster_full.lua,
       overworld/sprite_frames_full.lua, overworld/sprite_gender_cosmetic.lua,
       and a full resolution report (paths below).

  Nothing here touches main.lua, custom_sprite_species.lua or
  sprite_frames.lua -- Phase 1 only produces new, additive data files.
#>

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
$RepoRoot        = "C:\Proyectos\DynamaxRecomp\GalarGmaxDex"
$EngineRoot      = "C:\Proyectos\DynamaxRecomp\gen1recomp-dev\gen1recomp-dev"
$NationalDexRoot = "C:\Users\daemo\AppData\Roaming\pokemon-love2d\mods\national_dex"

$FrontDir = Join-Path $RepoRoot "assets\front"
$BackDir  = Join-Path $RepoRoot "assets\back"

$OutRosterPath   = Join-Path $RepoRoot "species\sprite_pack_roster_full.lua"
$OutFramesPath   = Join-Path $RepoRoot "overworld\sprite_frames_full.lua"
$OutCosmeticPath = Join-Path $RepoRoot "overworld\sprite_gender_cosmetic.lua"
$ReportPath      = "C:\Users\daemo\AppData\Local\Temp\claude\C--Proyectos-DynamaxRecomp\fb81b782-abf7-463b-936d-5989bd98387b\scratchpad\sprite_pack_resolution_report.md"

# ===========================================================================
# STEP 1 -- authoritative native vanilla species id list (251: Kanto+Johto)
# ===========================================================================
function Get-NativeVanillaList {
    # Kanto 151: gen1recomp-dev\data\generated\pokemon.lua is generated by
    # tools/build_data.py directly from the canonical Red ROM's BaseStats /
    # MonsterNames tables -- this is the real in-engine spelling convention
    # (e.g. FARFETCHD, MR_MIME, NIDORAN_F -- single underscore, no filler).
    $pokemonLuaPath = Join-Path $EngineRoot "data\generated\pokemon.lua"
    $kantoIds = Select-String -Path $pokemonLuaPath -Pattern '^  ([A-Z0-9_]+) = \{' |
        ForEach-Object { $_.Matches[0].Groups[1].Value }

    # Johto 152-251: tools/rom_manifest_gold.json's pokemonAssets keys (a
    # generation:2 manifest, confirmed by src/core/GameVersion.lua as the
    # Gold/Johto import manifest). Its own spelling convention differs
    # slightly from pokemon.lua's for 2 Kanto species it also lists
    # (FARFETCH_D, MR__MIME vs the real FARFETCHD, MR_MIME) -- those 2 are
    # dropped here since the Kanto set above already has the correct
    # spelling; every other Johto-only name was cross-validated against
    # national_dex's national.lua register table (which registers Johto
    # 152-251 as plain species for Red-context play) and matched exactly.
    $manifestPath = Join-Path $EngineRoot "tools\rom_manifest_gold.json"
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    $goldNames = $manifest.pokemonAssets.PSObject.Properties.Name
    $johtoOnly = $goldNames | Where-Object {
        ($kantoIds -notcontains $_) -and $_ -ne "FARFETCH_D" -and $_ -ne "MR__MIME"
    }

    return ($kantoIds + $johtoOnly) | Select-Object -Unique
}

# ===========================================================================
# STEP 1b -- parse national_dex's national.lua into flat records
# ===========================================================================
function Get-NationalRecords {
    $path = Join-Path $NationalDexRoot "data\species\generated\national.lua"
    $lines = Get-Content -LiteralPath $path -Encoding UTF8

    $records = New-Object System.Collections.Generic.List[object]
    $section = $null
    $curKey = $null; $curId = $null; $curDex = $null; $curForm = $null; $curBaseSpecies = $null
    $inRecord = $false

    function Flush {
        if ($inRecord -and $curKey) {
            $records.Add([PSCustomObject]@{
                section = $section; key = $curKey; id = $curId; dex = $curDex
                form = $curForm; baseSpecies = $curBaseSpecies
            })
        }
    }

    foreach ($line in $lines) {
        if ($line -match '^\s*patch = \{\s*$')    { $section = "patch"; continue }
        if ($line -match '^\s*register = \{\s*$') { $section = "register"; continue }
        if ($line -match '^\s*text = \{\s*$')     { $section = "text"; continue }

        if ($line -match '^    ([A-Za-z0-9_]+) = \{\s*$') {
            Flush
            $curKey = $matches[1]; $curId = $null; $curDex = $null; $curForm = $null; $curBaseSpecies = $null
            $inRecord = $true
            continue
        }
        if ($inRecord -and $line -match '^    \},\s*$') {
            Flush
            $inRecord = $false; $curKey = $null
            continue
        }
        if ($inRecord) {
            if ($line -match '^\s*id = "([^"]+)",?\s*$')          { $curId = $matches[1]; continue }
            if ($line -match '^\s*dex = (-?\d+),?\s*$')            { $curDex = [int]$matches[1]; continue }
            if ($line -match '^\s*form = "([^"]+)",?\s*$')         { $curForm = $matches[1]; continue }
            if ($line -match '^\s*baseSpecies = "([^"]+)",?\s*$')  { $curBaseSpecies = $matches[1]; continue }
        }
    }
    Flush

    return $records
}

# ===========================================================================
# STEP 2 -- enumerate + categorize folder tokens
# ===========================================================================
function Get-FolderTokens {
    $tokens = Get-ChildItem -LiteralPath $FrontDir -Directory | Select-Object -ExpandProperty Name
    return $tokens | Where-Object { $_ -ne "000" }
}

function Get-TokenCategory([string]$t) {
    if ($t -match '_MEGA')   { return "mega" }
    if ($t -match '_F$')     { return "female" }
    if ($t -match '_(\d+)$') { return "numeric" }
    return "plain"
}

# ===========================================================================
# MAIN
# ===========================================================================
Write-Host "== Phase 1 sprite pack generator =="

$native = Get-NativeVanillaList
Write-Host ("Native vanilla list: {0} ids" -f $native.Count)

$nationalRecords = Get-NationalRecords
$formRecords = $nationalRecords | Where-Object { $_.section -eq "register" -and $_.form }
$allNationalIds = ($nationalRecords | Select-Object -ExpandProperty id) | Select-Object -Unique
Write-Host ("national.lua records: {0} (patch={1}, register={2}, of which forms={3})" -f `
    $nationalRecords.Count, `
    (@($nationalRecords | Where-Object { $_.section -eq "patch" })).Count, `
    (@($nationalRecords | Where-Object { $_.section -eq "register" })).Count, `
    (@($formRecords)).Count)

$allTokens = Get-FolderTokens
Write-Host ("Folder tokens (excl. 000): {0}" -f $allTokens.Count)

$plainTokens  = New-Object System.Collections.Generic.List[string]
$megaTokens   = New-Object System.Collections.Generic.List[string]
$femaleTokens = New-Object System.Collections.Generic.List[string]
$numericTokens= New-Object System.Collections.Generic.List[string]
foreach ($t in $allTokens) {
    switch (Get-TokenCategory $t) {
        "mega"    { $megaTokens.Add($t) }
        "female"  { $femaleTokens.Add($t) }
        "numeric" { $numericTokens.Add($t) }
        default   { $plainTokens.Add($t) }
    }
}
Write-Host ("  plain={0} mega={1} female={2} numeric={3}" -f `
    $plainTokens.Count, $megaTokens.Count, $femaleTokens.Count, $numericTokens.Count)

# Resolution accumulators
$resolved = New-Object System.Collections.Generic.List[object]   # {token,id,category,note}
$skipped  = New-Object System.Collections.Generic.List[object]   # {token,category,reason}

# ---------------------------------------------------------------------------
# PLAIN resolution
# ---------------------------------------------------------------------------
# Build a verified, collision-free "underscore-stripped id -> real id" map
# across the FULL known-id universe (native vanilla + all national.lua ids)
# once, up front -- this lets folder tokens that dropped an underscore
# (HOOH -> HO_OH, TAPUKOKO -> TAPU_KOKO, MRMIME -> MR_MIME, ...) resolve via
# a mechanical, auditable normalization instead of a guess. Collisions (two
# distinct real ids collapsing to the same stripped string) would abort the
# whole pass rather than silently pick one.
$knownIdUniverse = ($native + $allNationalIds) | Select-Object -Unique
$strippedMap = @{}
$stripCollisions = New-Object System.Collections.Generic.List[string]
foreach ($id in $knownIdUniverse) {
    $stripped = $id -replace '_', ''
    if ($strippedMap.ContainsKey($stripped)) {
        $stripCollisions.Add("$stripped <- $id AND $($strippedMap[$stripped])")
    } else {
        $strippedMap[$stripped] = $id
    }
}
if ($stripCollisions.Count -gt 0) {
    Write-Warning "Underscore-stripped id collisions detected -- normalization pass DISABLED for safety:"
    $stripCollisions | ForEach-Object { Write-Warning "  $_" }
    $strippedMap = @{}
}

# Two known, unambiguous non-underscore abbreviations that the stripping
# pass alone can't catch (folder used FE/MA rather than F/M).
$plainManualOverrides = @{
    "NIDORANFE" = "NIDORAN_F"
    "NIDORANMA" = "NIDORAN_M"
}

foreach ($t in $plainTokens) {
    if ($native -contains $t) {
        $resolved.Add([PSCustomObject]@{ token=$t; id=$t; category="plain"; note="exact match, native vanilla" })
    } elseif ($allNationalIds -contains $t) {
        $resolved.Add([PSCustomObject]@{ token=$t; id=$t; category="plain"; note="exact match, national_dex" })
    } elseif ($plainManualOverrides.ContainsKey($t)) {
        $mapped = $plainManualOverrides[$t]
        $resolved.Add([PSCustomObject]@{ token=$t; id=$mapped; category="plain"; note="known abbreviation (FE/MA -> F/M)" })
    } elseif ($strippedMap.ContainsKey($t)) {
        $mapped = $strippedMap[$t]
        $resolved.Add([PSCustomObject]@{ token=$t; id=$mapped; category="plain"; note="underscore-stripped match (verified collision-free)" })
    } else {
        $skipped.Add([PSCustomObject]@{ token=$t; category="plain"; reason="no matching registered species (not in native vanilla 251 or national_dex, even after underscore-stripped normalization)" })
    }
}

# ---------------------------------------------------------------------------
# MEGA-FAMILY resolution
# ---------------------------------------------------------------------------
foreach ($t in $megaTokens) {
    $idx = $t.IndexOf("_MEGA")
    $base = $t.Substring(0, $idx)
    $formLabel = $t.Substring($idx + 1)  # "MEGA", "MEGA_X", "MEGA_FORMA_..."

    $matches_ = @($formRecords | Where-Object { $_.baseSpecies -eq $base -and $_.form -eq $formLabel })
    if ($matches_.Count -eq 1) {
        $resolved.Add([PSCustomObject]@{ token=$t; id=$matches_[0].id; category="mega"; note="baseSpecies=$base form=$formLabel" })
    } elseif ($matches_.Count -gt 1) {
        $skipped.Add([PSCustomObject]@{ token=$t; category="mega-family"; reason="multiple matching records for baseSpecies=$base form=$formLabel (ambiguous)" })
    } else {
        # Special-cased explanation for the one real ambiguity found during
        # verification: Meowstic's only Mega records are gender-split
        # (MALE_MEGA / FEMALE_MEGA); the folder token doesn't specify which.
        if ($base -eq "MEOWSTIC" -and $formLabel -eq "MEGA") {
            $skipped.Add([PSCustomObject]@{ token=$t; category="mega-family"; reason="MEOWSTIC's real Mega forms are gender-split (MALE_MEGA/FEMALE_MEGA in national_dex); the plain MEOWSTIC_MEGA folder token does not specify which, so it cannot be resolved without guessing" })
        } else {
            $skipped.Add([PSCustomObject]@{ token=$t; category="mega-family"; reason="no canonical Mega/alt-form exists for this species in national_dex (baseSpecies=$base form=$formLabel not found)" })
        }
    }
}

# ---------------------------------------------------------------------------
# NUMERIC-SUFFIX resolution
# ---------------------------------------------------------------------------
# Vivillon/Alcremie are excluded outright per explicit user instruction --
# base-only, all numbered pattern/flavor variants dropped.
$excludedNumeric = @($numericTokens | Where-Object { $_ -match '^(VIVILLON|ALCREMIE)_\d+$' })
foreach ($t in $excludedNumeric) {
    $skipped.Add([PSCustomObject]@{ token=$t; category="numeric"; reason="excluded by instruction (cosmetic pattern/flavor variant, base-only)" })
}
$numericToResolve = @($numericTokens | Where-Object { $_ -notmatch '^(VIVILLON|ALCREMIE)_\d+$' })

# Group remaining numeric tokens by base species.
$numGroups = @{}
foreach ($t in $numericToResolve) {
    if ($t -match '^(.+)_(\d+)$') {
        $base = $matches[1]
        if (-not $numGroups.ContainsKey($base)) { $numGroups[$base] = New-Object System.Collections.Generic.List[string] }
        $numGroups[$base].Add($t)
    }
}

# Tier 2: a short, individually-verified hand list for well-known
# multi-form species where the real in-game (or Pokedex-fixed) form order
# is unambiguous -- NOT alphabetical guessing. Each id below is re-verified
# against national.lua's actual form records below before being trusted;
# if verification fails for any entry, that specific token falls through
# to Tier 3 rather than being forced.
#   DEOXYS/ROTOM: literal in-game "change form" menu order.
#   CASTFORM: canonical weather-form order (Bulbapedia/every game datamine).
#   ORICORIO/WORMADAM/CRAMORANT/LYCANROC/SQUAWKABILLY/TAUROS/TERAPAGOS:
#     fixed Pokedex/story form-listing order used consistently in-game.
#   BASCULIN: folder numbering starts at _2 (not _1), consistent with "_1"
#     being reserved for the base Red-Striped (the plain BASCULIN folder);
#     Blue-Striped predates White-Striped by 3 generations, matching _2/_3.
#   DARMANITAN: Bulbapedia's fixed infobox form order (Standard/Zen/
#     Galar-Standard/Galar-Zen), Standard being the plain DARMANITAN folder.
$tier2Map = @{
    "DEOXYS"        = @{ "1"="ATTACK"; "2"="DEFENSE"; "3"="SPEED" }
    "ROTOM"         = @{ "1"="HEAT"; "2"="WASH"; "3"="FROST"; "4"="FAN"; "5"="MOW" }
    "CASTFORM"      = @{ "1"="SUNNY"; "2"="RAINY"; "3"="SNOWY" }
    "ORICORIO"      = @{ "1"="POM_POM"; "2"="PAU"; "3"="SENSU" }
    "WORMADAM"      = @{ "1"="SANDY"; "2"="TRASH" }
    "CRAMORANT"     = @{ "1"="GULPING"; "2"="GORGING" }
    "TERAPAGOS"     = @{ "1"="TERASTAL"; "2"="STELLAR" }
    "TAUROS"        = @{ "1"="PALDEA_COMBAT_BREED"; "2"="PALDEA_BLAZE_BREED"; "3"="PALDEA_AQUA_BREED" }
    "SQUAWKABILLY"  = @{ "1"="BLUE_PLUMAGE"; "2"="YELLOW_PLUMAGE"; "3"="WHITE_PLUMAGE" }
    "LYCANROC"      = @{ "1"="MIDNIGHT"; "2"="DUSK" }
    "BASCULIN"      = @{ "2"="BLUE_STRIPED"; "3"="WHITE_STRIPED" }
    "DARMANITAN"    = @{ "1"="ZEN"; "2"="GALAR_STANDARD"; "3"="GALAR_ZEN" }
}

foreach ($base in ($numGroups.Keys | Sort-Object)) {
    $tokens = $numGroups[$base]
    $nonMegaForms = @($formRecords | Where-Object { $_.baseSpecies -eq $base -and $_.form -notmatch 'MEGA|GMAX|GIGANTAMAX' })

    if ($tokens.Count -eq 1 -and $nonMegaForms.Count -eq 1) {
        # Tier 1: exactly one non-Mega/Gmax alt form AND exactly one numeric
        # folder for this species -- a safe 1:1 identity match, not a guess.
        $resolved.Add([PSCustomObject]@{ token=$tokens[0]; id=$nonMegaForms[0].id; category="numeric-tier1"; note="baseSpecies=$base form=$($nonMegaForms[0].form), single unambiguous alt form" })
        continue
    }

    if ($tier2Map.ContainsKey($base)) {
        $formMap = $tier2Map[$base]
        $allOk = $true
        $pending = New-Object System.Collections.Generic.List[object]
        foreach ($tok in $tokens) {
            if ($tok -match '_(\d+)$') {
                $numSuffix = $matches[1]
                if ($formMap.ContainsKey($numSuffix)) {
                    $expectedForm = $formMap[$numSuffix]
                    $match = @($nonMegaForms | Where-Object { $_.form -eq $expectedForm })
                    if ($match.Count -eq 1) {
                        $pending.Add([PSCustomObject]@{ token=$tok; id=$match[0].id; category="numeric-tier2"; note="hand-mapped + verified: baseSpecies=$base form=$expectedForm" })
                    } else {
                        $allOk = $false
                    }
                } else {
                    $allOk = $false
                }
            }
        }
        if ($allOk -and $pending.Count -eq $tokens.Count) {
            foreach ($p in $pending) { $resolved.Add($p) }
            continue
        }
        # fall through to Tier 3 if verification failed for any token in the group
    }

    # Tier 3: insufficient evidence -- explain WHY (mismatch shape) rather
    # than a generic message, so the report is auditable.
    $formCount = $nonMegaForms.Count
    $formList = if ($formCount -gt 0) { ($nonMegaForms | ForEach-Object { $_.form }) -join "," } else { "(none)" }
    $reason = "insufficient evidence to confidently map numeric variant(s) to a real form -- $($tokens.Count) numeric folder(s) [$($tokens -join ',')] vs $formCount registered non-Mega/Gmax alt form(s) [$formList] for baseSpecies=$base; no safe 1:1 identity match and no verified Tier 2 domain mapping covers this case"
    foreach ($tok in $tokens) {
        $skipped.Add([PSCustomObject]@{ token=$tok; category="numeric"; reason=$reason })
    }
}

# ---------------------------------------------------------------------------
# FEMALE ("_F") resolution -- cosmetic bucket, except the 4 real _FEMALE ids
# ---------------------------------------------------------------------------
$realFemaleSpecies = @{
    "MEOWSTIC"    = "MEOWSTIC_FEMALE"
    "INDEEDEE"    = "INDEEDEE_FEMALE"
    "BASCULEGION" = "BASCULEGION_FEMALE"
    "OINKOLOGNE"  = "OINKOLOGNE_FEMALE"
}
# Universe of ids resolved so far (plain + mega + numeric tiers), so a
# compound token like SNEASEL_1_F can resolve against SNEASEL_1's resolved
# real id (SNEASEL_HISUI) rather than being treated as unresolvable.
$resolvedByToken = @{}
foreach ($r in $resolved) { $resolvedByToken[$r.token] = $r.id }

$cosmeticFemale = New-Object System.Collections.Generic.List[object]  # {baseToken, resolvedId, folderToken}

foreach ($t in $femaleTokens) {
    $baseToken = $t.Substring(0, $t.Length - 2)  # strip trailing "_F"

    if ($realFemaleSpecies.ContainsKey($baseToken)) {
        # Would resolve directly as a distinct roster id if this exact
        # folder shape ever appears (none currently do -- the 4 known
        # species use numeric-suffix folders instead, handled above).
        $resolved.Add([PSCustomObject]@{ token=$t; id=$realFemaleSpecies[$baseToken]; category="female-real"; note="real distinct _FEMALE id, not cosmetic" })
        continue
    }

    if ($resolvedByToken.ContainsKey($baseToken)) {
        $realId = $resolvedByToken[$baseToken]
        $cosmeticFemale.Add([PSCustomObject]@{ baseToken=$baseToken; resolvedId=$realId; folderToken=$t })
    } elseif ($native -contains $baseToken -or $allNationalIds -contains $baseToken) {
        # base token itself is a real id even though it wasn't independently
        # walked through the plain-token loop (defensive fallback).
        $cosmeticFemale.Add([PSCustomObject]@{ baseToken=$baseToken; resolvedId=$baseToken; folderToken=$t })
    } else {
        $skipped.Add([PSCustomObject]@{ token=$t; category="female"; reason="base token '$baseToken' does not resolve to a real registered species (skipped or unresolved itself), so no species exists to attach this cosmetic female art to" })
    }
}

Write-Host ("Resolved: {0}  Skipped: {1}  Cosmetic-female folders: {2}" -f $resolved.Count, $skipped.Count, $cosmeticFemale.Count)

# ===========================================================================
# STEP 4 -- measure frame data
# ===========================================================================
function Measure-Side([string]$token, [string]$sideDir) {
    $dir = Join-Path $sideDir $token
    if (-not (Test-Path -LiteralPath $dir)) { return $null }
    $frames = Get-ChildItem -LiteralPath $dir -Filter "*.png" | Sort-Object Name
    if ($frames.Count -eq 0) { return $null }
    $first = $frames[0].FullName
    $img = [System.Drawing.Image]::FromFile($first)
    $w = $img.Width; $h = $img.Height
    $img.Dispose()
    $size = [Math]::Max($w, $h)
    return [PSCustomObject]@{ count = $frames.Count; size = $size; w = $w; h = $h }
}

function Measure-Token([string]$token) {
    $front = Measure-Side $token $FrontDir
    $back  = Measure-Side $token $BackDir
    return [PSCustomObject]@{
        front = if ($front) { $front.count } else { 0 }
        frontSize = if ($front) { $front.size } else { 0 }
        back = if ($back) { $back.count } else { 0 }
        backSize = if ($back) { $back.size } else { 0 }
    }
}

Write-Host "Measuring frame data for resolved roster..."
$measurements = @{}  # token -> measurement (measure by FOLDER TOKEN, not resolved id)
$rosterEntries = New-Object System.Collections.Generic.List[object]  # {id, token, m}
$seenIds = @{}
foreach ($r in $resolved) {
    if ($r.category -eq "female-real") { continue }  # handled with numeric/plain ids normally; but no folder token "_F" exists for these on disk today
    if ($seenIds.ContainsKey($r.id)) {
        Write-Warning "Duplicate resolved id '$($r.id)' from tokens '$($seenIds[$r.id])' and '$($r.token)' -- keeping first"
        continue
    }
    $m = Measure-Token $r.token
    $measurements[$r.token] = $m
    $rosterEntries.Add([PSCustomObject]@{ id=$r.id; token=$r.token; m=$m })
    $seenIds[$r.id] = $r.token
}
Write-Host ("Measured {0} roster entries." -f $rosterEntries.Count)

Write-Host "Measuring frame data for cosmetic female folders..."
$cosmeticEntries = New-Object System.Collections.Generic.List[object]  # {baseId, folderToken, m}
$seenCosmeticBase = @{}
foreach ($c in $cosmeticFemale) {
    if ($seenCosmeticBase.ContainsKey($c.resolvedId)) {
        Write-Warning "Duplicate cosmetic-female base id '$($c.resolvedId)' from folders '$($seenCosmeticBase[$c.resolvedId])' and '$($c.folderToken)' -- keeping first"
        continue
    }
    $m = Measure-Token $c.folderToken
    $cosmeticEntries.Add([PSCustomObject]@{ baseId=$c.resolvedId; folderToken=$c.folderToken; m=$m })
    $seenCosmeticBase[$c.resolvedId] = $c.folderToken
}
Write-Host ("Measured {0} cosmetic-female entries." -f $cosmeticEntries.Count)

# ===========================================================================
# STEP 5 -- emit output files
# ===========================================================================
function Lua-QuoteId([string]$id) {
    # All ids here are [A-Z0-9_]+ (verified against national.lua/native list
    # parsing above), so a bare identifier key is always valid Lua.
    return $id
}

# --- species/sprite_pack_roster_full.lua ---
$rosterSorted = $rosterEntries | Sort-Object id
$rosterLines = New-Object System.Collections.Generic.List[string]
$rosterLines.Add("-- Full-roster battle sprite pack -- flat array of every species/form id")
$rosterLines.Add("-- resolved (Phase 1, tools/generate_sprite_pack_data.ps1) from the manually")
$rosterLines.Add("-- sliced assets/front|back/<TOKEN>/NNN.png battle-sprite pack, cross-")
$rosterLines.Add("-- referenced against national_dex's national.lua and the engine's own")
$rosterLines.Add("-- native vanilla Kanto+Johto species list. See")
$rosterLines.Add("-- overworld/sprite_frames_full.lua for this list's frame-count/size data,")
$rosterLines.Add("-- and the offline resolution report for every token that was intentionally")
$rosterLines.Add("-- skipped (nothing here was guessed -- every id was independently verified")
$rosterLines.Add("-- as a real national_dex or native-vanilla record before being included).")
$rosterLines.Add("--")
$rosterLines.Add("-- This is a SEPARATE roster from species/custom_sprite_species.lua, which")
$rosterLines.Add("-- stays scoped to the Gigantamax-capable species' own bundled art. This")
$rosterLines.Add("-- file is Phase 1 output only -- wiring it into installSpriteAssetPacks /")
$rosterLines.Add("-- reapplySpritePacks (main.lua) is Phase 2, not done here.")
$rosterLines.Add("return {")
$col = New-Object System.Collections.Generic.List[string]
foreach ($e in $rosterSorted) { $col.Add('"' + $e.id + '"') }
for ($i = 0; $i -lt $col.Count; $i += 6) {
    $chunk = $col[$i..([Math]::Min($i + 5, $col.Count - 1))]
    $rosterLines.Add("  " + ($chunk -join ", ") + ",")
}
$rosterLines.Add("}")
Set-Content -LiteralPath $OutRosterPath -Value $rosterLines -Encoding UTF8
Write-Host "Wrote $OutRosterPath"

# --- overworld/sprite_frames_full.lua ---
$framesLines = New-Object System.Collections.Generic.List[string]
$framesLines.Add("-- Full-roster frame counts + native pixel size per species/side, generated")
$framesLines.Add("-- directly from the lossless slicing pass (assets/front/<ID>/NNN.png,")
$framesLines.Add("-- assets/back/<ID>/NNN.png -- crop-only, no resize, every frame preserves")
$framesLines.Add("-- its source pixels exactly), same shape/semantics as overworld/")
$framesLines.Add("-- sprite_frames.lua (that file stays scoped to the original 51-species")
$framesLines.Add("-- Gigantamax roster; this is the Phase 1 full-roster companion, keyed by")
$framesLines.Add("-- resolved national_dex/native-vanilla id, not raw folder token).")
$framesLines.Add("-- Frame counts and native sizes both vary per species -- no fixed")
$framesLines.Add("-- convention, confirmed by direct measurement.")
$framesLines.Add("-- main.lua computes each species battleScaleFront/battleScaleBack from")
$framesLines.Add("-- the size fields here (56 / native size) -- see BattleState.lua")
$framesLines.Add("-- BATTLE_SCALE_DEFAULT/resolveBattleScale in the real engine source.")
$framesLines.Add("")
$framesLines.Add("return {")
foreach ($e in $rosterSorted) {
    $m = $e.m
    $framesLines.Add(("  {0} = {{ front = {1}, frontSize = {2}, back = {3}, backSize = {4} }}," -f `
        (Lua-QuoteId $e.id), $m.front, $m.frontSize, $m.back, $m.backSize))
}
$framesLines.Add("}")
Set-Content -LiteralPath $OutFramesPath -Value $framesLines -Encoding UTF8
Write-Host "Wrote $OutFramesPath"

# --- overworld/sprite_gender_cosmetic.lua ---
$cosmeticSorted = $cosmeticEntries | Sort-Object baseId
$cosmeticLines = New-Object System.Collections.Generic.List[string]
$cosmeticLines.Add("-- Cosmetic FEMALE battle-sprite lookup, keyed by BASE species id.")
$cosmeticLines.Add("--")
$cosmeticLines.Add("-- These are NOT separate species/content ids -- national_dex has no")
$cosmeticLines.Add("-- registered '<ID>_FEMALE' record for any species listed here (the 4")
$cosmeticLines.Add("-- species that DO have a real separate _FEMALE id -- Meowstic, Indeedee,")
$cosmeticLines.Add("-- Basculegion, Oinkologne -- are wired as ordinary distinct roster entries")
$cosmeticLines.Add("-- in sprite_pack_roster_full.lua instead, not through this table).")
$cosmeticLines.Add("--")
$cosmeticLines.Add("-- Purely a battle-time cosmetic sprite swap: a later phase should check the")
$cosmeticLines.Add("-- battler's rolled gender, and if female AND this table has an entry for")
$cosmeticLines.Add("-- that species, source live battle frames from assets/<side>/<folderToken>/")
$cosmeticLines.Add("-- instead of assets/<side>/<ID>/ -- falling back to the base id's art if the")
$cosmeticLines.Add("-- species has no entry here, same silent-safe-fallback convention already")
$cosmeticLines.Add("-- used elsewhere in this pipeline. Not wired up anywhere yet -- Phase 1")
$cosmeticLines.Add("-- only produces this data; the hook lands in a later phase.")
$cosmeticLines.Add("")
$cosmeticLines.Add("return {")
foreach ($e in $cosmeticSorted) {
    $m = $e.m
    $cosmeticLines.Add(("  {0} = {{ folder = `"{1}`", front = {2}, frontSize = {3}, back = {4}, backSize = {5} }}," -f `
        (Lua-QuoteId $e.baseId), $e.folderToken, $m.front, $m.frontSize, $m.back, $m.backSize))
}
$cosmeticLines.Add("}")
Set-Content -LiteralPath $OutCosmeticPath -Value $cosmeticLines -Encoding UTF8
Write-Host "Wrote $OutCosmeticPath"

# --- resolution report ---
$reportLines = New-Object System.Collections.Generic.List[string]
$reportLines.Add("# Sprite pack Phase 1 resolution report")
$reportLines.Add("")
$reportLines.Add("Generated by ``tools/generate_sprite_pack_data.ps1``.")
$reportLines.Add("")
$reportLines.Add("## Totals")
$reportLines.Add("")
$reportLines.Add("- Folder tokens processed (excl. ``000``): **$($allTokens.Count)**")
$reportLines.Add("  - plain: $($plainTokens.Count)")
$reportLines.Add("  - mega-family: $($megaTokens.Count)")
$reportLines.Add("  - female (``_F``): $($femaleTokens.Count)")
$reportLines.Add("  - numeric-suffix: $($numericTokens.Count)")
$reportLines.Add("- Resolved into the roster: **$($rosterEntries.Count)**")
foreach ($cat in @("plain","mega","numeric-tier1","numeric-tier2","female-real")) {
    $n = @($resolved | Where-Object { $_.category -eq $cat }).Count
    $reportLines.Add("  - ${cat}: $n")
}
$reportLines.Add("- Cosmetic-female folders resolved: **$($cosmeticEntries.Count)**")
$reportLines.Add("- Skipped/unresolved tokens: **$($skipped.Count)**")
foreach ($cat in ($skipped | Select-Object -ExpandProperty category -Unique | Sort-Object)) {
    $n = @($skipped | Where-Object { $_.category -eq $cat }).Count
    $reportLines.Add("  - ${cat}: $n")
}
$reportLines.Add("")
$reportLines.Add("## Full skip/unresolved list")
$reportLines.Add("")
$reportLines.Add("| Token | Category | Reason |")
$reportLines.Add("|---|---|---|")
foreach ($s in ($skipped | Sort-Object category, token)) {
    $reportLines.Add("| $($s.token) | $($s.category) | $($s.reason) |")
}
$reportLines.Add("")
$reportLines.Add("## Resolved roster (id <- source token)")
$reportLines.Add("")
$reportLines.Add("| Id | Token | Category | Note |")
$reportLines.Add("|---|---|---|---|")
foreach ($r in ($resolved | Where-Object { $_.category -ne "female-real" } | Sort-Object id)) {
    $reportLines.Add("| $($r.id) | $($r.token) | $($r.category) | $($r.note) |")
}
$reportLines.Add("")
$reportLines.Add("## Cosmetic female folders")
$reportLines.Add("")
$reportLines.Add("| Base id | Folder token |")
$reportLines.Add("|---|---|")
foreach ($c in $cosmeticSorted) {
    $reportLines.Add("| $($c.baseId) | $($c.folderToken) |")
}
Set-Content -LiteralPath $ReportPath -Value $reportLines -Encoding UTF8
Write-Host "Wrote $ReportPath"

Write-Host "== Done =="
